// The full round trip for an attachment link: the renderer builds it, marked parses it, and the
// main process decodes it back to a filename on disk.
//
// This exists because that chain was broken and nothing noticed. A markdown link target is a URL,
// not a path, so a filename containing a space — or a paren, or a bracket — produced a link marked
// refused to parse, and the note simply showed `![x](attachments/a b.png)` as literal text. No
// image, no link, no error. Three of the five attachments in the first real project checked were
// unreachable this way, and one of those names ("diamond 1.png") was generated by our OWN
// de-duplication: dropping the same file twice manufactured a broken link.
//
// All three ends are asserted together on purpose. Testing the encoder alone would have passed
// while the decoder disagreed with it.
const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

// The vendored marked is UMD, so it loads straight under CommonJS.
const marked = require('../renderer/vendor/marked.umd.js');

// editor/attachments.js is a browser IIFE that publishes onto `window`.
function loadAttach() {
  const win = {};
  const src = fs.readFileSync(path.join(__dirname, '..', 'renderer', 'editor', 'attachments.js'), 'utf8');
  new Function('window', src).call({ window: win }, win);
  return win.Attach;
}

const Attach = loadAttach();
const { attachmentName } = require('../src/main/services/storage');

const render = (md) => marked.parse(md, { breaks: true, gfm: true }).trim();
const srcOf = (html) => (/<(?:img[^>]+src|a[^>]+href)="([^"]*)"/.exec(html) || [])[1] || null;

// Every one of these is a filename that occurs in real use; every one broke before encoding.
const NAMES = [
  'icon.png',                                        // the only shape that ever worked
  'diamond 1.png',                                   // our own de-dup suffix
  'Screenshot 2024-06-19 124421.png',
  'CD 526 revision 3 Spacing of road gullies-web.pdf',
  'plan (rev A).png',                                // encodeURI leaves parens alone; ) ends the link
  'plan [rev A].png',
  '50% slope.png',
  'Détail béton.png',                                // non-ASCII
];

for (const name of NAMES) {
  test(`"${name}" survives the round trip`, () => {
    const md = Attach.markdownLink('attachments/' + name);
    const target = srcOf(render(md));

    assert.ok(target, `marked did not parse a link out of ${JSON.stringify(md)}`);
    assert.ok(target.startsWith('attachments/'), `resolveReadingView keys off this prefix, got ${target}`);
    assert.strictEqual(attachmentName(target), name, 'the main process must recover the exact filename');
  });
}

test('images get an embed, other files get a plain link', () => {
  assert.ok(Attach.markdownLink('attachments/photo.png').startsWith('!['));
  assert.ok(Attach.markdownLink('attachments/spec.pdf').startsWith('['));
});

test('the label stays readable — it is display text, not a URL', () => {
  // Encoding the label too would show the user "diamond%201.png" in their note.
  assert.match(Attach.markdownLink('attachments/diamond 1.png'), /^!\[diamond 1\.png\]/);
});

test('brackets in a name are escaped in the label so they cannot end it early', () => {
  const md = Attach.markdownLink('attachments/plan [rev A].png');
  assert.match(md, /^!\[plan \\\[rev A\\\]\.png\]/);
  assert.ok(srcOf(render(md)), 'and it still parses');
});

test('a raw, unencoded link is exactly what used to break', () => {
  // Pinning the old behaviour, so the reason this module exists stays legible.
  assert.strictEqual(srcOf(render('![x](attachments/a b.png)')), null);
  assert.ok(srcOf(render(Attach.markdownLink('attachments/a b.png'))), 'and the encoded form works');
});
